[package]
name = "dirdiff"
version = "0.1.0"
authors = ["Andres Osinski <andres.osinski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.9.1"
walkdir = "2"
